name: Automatic Release

on:
  push:
    tags:
      - "v*" # Trigger on tags starting with 'v'
  workflow_dispatch:

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Determine if pre-release
        id: pre_release_check
        run: |
          if [[ "${GITHUB_REF_NAME}" == *-* ]]; then
            echo "Pre-release detected: ${GITHUB_REF_NAME}"
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "Release detected: ${GITHUB_REF_NAME}"
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "None")

          if [ "$PREV_TAG" != "None" ]; then
            echo "Generating changelog between $PREV_TAG and $GITHUB_REF"
            git log "$PREV_TAG"..HEAD --oneline > changelog.txt
          else
            echo "First release, no previous changelog." > changelog.txt
          fi

          cat changelog.txt
          echo "CHANGES=$(cat changelog.txt)" >> $GITHUB_ENV

      - name: Create Release
        run: gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "${CHANGES}" \
          --prerelease "${IS_PRERELEASE}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
