name: Automatic Release

on:
  push:
    tags:
      - "v*" # Trigger on tags starting with 'v'

jobs:
  release:
    name: Create Release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment (if changelog needs Python tools)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Determine if the tag is a pre-release
      - name: Determine if pre-release
        id: pre_release_check
        run: |
          if [[ "${GITHUB_REF_NAME}" == *-* ]]; then
            echo "Pre-release detected: ${GITHUB_REF_NAME}"
            echo "::set-output name=is_prerelease::true"
          else
            echo "Release detected: ${GITHUB_REF_NAME}"
            echo "::set-output name=is_prerelease::false"
          fi

      # Generate changelog
      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "None")

          if [ "$PREV_TAG" != "None" ]; then
            echo "Generating changelog between $PREV_TAG and $GITHUB_REF"
            git log "$PREV_TAG"..HEAD --oneline > changelog.txt
          else
            echo "First release, no previous changelog." > changelog.txt
          fi

          cat changelog.txt
          echo "::set-output name=changes::$(cat changelog.txt | jq -Rsa .)"

      # Create GitHub release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: ${{ steps.pre_release_check.outputs.is_prerelease }}
